### ISSUE TITLE
activity log not working with left/right bound

### ISSUE THREAD

**Issue by rconstanzo** [madwort/improv-analysis#2]
The following shortcode shows complete activity log regardless of the bounding.

[improv-analysis unique_name="analysis13" audio_url="http://www.rodrigoconstanzo.com/analyses/PA 1.mp3" data_url="http://www.rodrigoconstanzo.com/analyses/PA 1.csv" audio_length="363.408" left_bound="82" right_bound="96" waveform=true bubble_chart=true activity_log=true]

**Comment by madwort** [comment]
Please verify & close.

**Comment by madwort** [comment]
Forgot to bump plugin version...
