### ISSUE TITLE
trend lines wiggly/jiggly when events are within milliseconds of each other

### ISSUE THREAD

**Issue by rconstanzo** [madwort/improv-analysis#3]
Trend chart in standalone and plugin version has angled line in trend charts:

http://rodrigoconstanzo.com/analyses/?q=pa1
http://rodrigoconstanzo.com/analyses/?q=otto1

**Comment by madwort** [comment]
Applies to master (standalone deployment) branch, does it also apply to wordpress-plugin branch?

**Comment by madwort** [comment]
Fix applied to both branches!
