### ISSUE TITLE
zoom=true does not display correct file/data

### ISSUE THREAD

**Issue by rconstanzo** [madwort/improv-analysis#4]
zoom=true displays default (Everything (1a)) play/zoom bar no matter what data is loaded.

[improv-analysis unique_name="analysis2" audio_url="http://www.rodrigoconstanzo.com/analyses/Everything 1b.mp3" data_url="http://www.rodrigoconstanzo.com/analyses/Everything 1b.csv" audio_length="165.887" left_bound="0" right_bound="165.887" bubble_chart=true waveform=true zoom=true]

**Comment by madwort** [comment]
Use as follows:

[improv-analysis unique_name="analysis2" audio_url="http://www.rodrigoconstanzo.com/analyses/Everything 1b.mp3" data_url="http://www.rodrigoconstanzo.com/analyses/Everything 1b.csv" video_url="http://vimeo.com/somestuff" analysis_name="Everything 1b" audio_length="165.887" left_bound="0" right_bound="165.887" bubble_chart=true waveform=true zoom=true]
